#ifndef __COSTANTS__
#define __COSTANTS__

#define GATE_AVAILABLE 1
#define GATE_IS_OPEN 2
#define GATE_AFTER_CLOSURE 3
#define CONTAINER_FULL 4
#define TMP_ALLARM 5

#define MAX_TIME_OPEN 5000
#define T2 3000
#define TIME_DEEPSLEEP 10000
#define MAX_TEMP 35
#define MAX_CONT_LEVEL 100


#define LCD_1 "PRESS OPEN TO ENTER WASTE"
#define LCD_2 "PRESS CLOSE WHEN DONE"
#define LCD_3 "WASTE RECEIVED"
#define LCD_4 "CONTAINER FULL"
#define LCD_5 "PROBLEM DETECTED"

#endif